services:
  web:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src/app
          target: /app/src/app
          initial_sync: true
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
